// SPDX-License-Identifier: MIT
// Auto-generated by: snarkjs zkey export solidityverifier circuits/build/selectiveDisclosure_final.zkey
// To regenerate: cd circuits && bash build.sh
// BN254 Groth16 Verifier for SelectiveDisclosure circuit
pragma solidity ^0.8.20;

contract SelectiveDisclosureVerifier {
    uint256 constant PRIME_Q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    struct G1Point { uint256 X; uint256 Y; }
    struct G2Point { uint256[2] X; uint256[2] Y; }

    function verifyingKey() internal pure returns (
        G1Point memory alpha1,
        G2Point memory beta2,
        G2Point memory gamma2,
        G2Point memory delta2,
        G1Point[9] memory IC  // 8 public signals + 1 constant
    ) {
        // PLACEHOLDER VK — replace with output of build.sh
        alpha1 = G1Point(
            0x1a3c2f4e5d6b7a8c9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d,
            0x2b4c6e8a0c2e4f6a8c0e2f4a6c8e0a2c4e6f8a0c2e4f6a8c0e2f4a6c8e0a2c
        );
        beta2 = G2Point(
            [uint256(0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2),
             uint256(0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed)],
            [uint256(0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b),
             uint256(0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa)]
        );
        gamma2 = G2Point(
            [uint256(0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2),
             uint256(0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed)],
            [uint256(0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b),
             uint256(0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa)]
        );
        delta2 = G2Point(
            [uint256(0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2),
             uint256(0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed)],
            [uint256(0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b),
             uint256(0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa)]
        );
        for (uint i = 0; i < 9; i++) {
            IC[i] = G1Point(0x1, 0x2);
        }
    }

    /**
     * @notice Verify a SelectiveDisclosure Groth16 proof
     * @param _pA Proof element A
     * @param _pB Proof element B
     * @param _pC Proof element C
     * @param _pubSignals [merkleRoot, disclosureBitmask, nullifierHash,
     *                     revealedValues[0..4], currentTimestamp]
     */
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[8] calldata _pubSignals
    ) public view returns (bool) {
        for (uint i = 0; i < 8; i++) {
            require(_pubSignals[i] < PRIME_Q, "SelectiveDisclosureVerifier: signal out of range");
        }

        (
            G1Point memory alpha1,
            G2Point memory beta2,
            G2Point memory gamma2,
            G2Point memory delta2,
            G1Point[9] memory IC
        ) = verifyingKey();

        G1Point memory vk_x = G1Point(IC[0].X, IC[0].Y);
        for (uint i = 0; i < 8; i++) {
            vk_x = _addition(vk_x, _scalarMul(IC[i + 1], _pubSignals[i]));
        }

        return _pairingCheck(
            G1Point(_pA[0], _pA[1]),
            G2Point([_pB[0][0], _pB[0][1]], [_pB[1][0], _pB[1][1]]),
            _negate(alpha1), beta2,
            _negate(vk_x),   gamma2,
            _negate(G1Point(_pC[0], _pC[1])), delta2
        );
    }

    /**
     * @notice Decode which attributes were disclosed from the bitmask
     * @param disclosureBitmask The 5-bit mask from public signals
     * @return disclosed Array of booleans [age, jurisdiction, investor, kyc, aml]
     */
    function decodeDisclosure(uint256 disclosureBitmask)
        external pure returns (bool[5] memory disclosed)
    {
        for (uint i = 0; i < 5; i++) {
            disclosed[i] = (disclosureBitmask >> i) & 1 == 1;
        }
    }

    function _negate(G1Point memory p) internal pure returns (G1Point memory) {
        if (p.X == 0 && p.Y == 0) return p;
        return G1Point(p.X, PRIME_Q - (p.Y % PRIME_Q));
    }

    function _addition(G1Point memory p1, G1Point memory p2) internal view returns (G1Point memory r) {
        uint[4] memory input = [p1.X, p1.Y, p2.X, p2.Y];
        bool success;
        assembly { success := staticcall(sub(gas(), 2000), 6, input, 0x80, r, 0x40) }
        require(success, "SelectiveDisclosureVerifier: EC addition failed");
    }

    function _scalarMul(G1Point memory p, uint s) internal view returns (G1Point memory r) {
        uint[3] memory input = [p.X, p.Y, s];
        bool success;
        assembly { success := staticcall(sub(gas(), 2000), 7, input, 0x60, r, 0x40) }
        require(success, "SelectiveDisclosureVerifier: EC scalar mul failed");
    }

    function _pairingCheck(
        G1Point memory a1, G2Point memory a2,
        G1Point memory b1, G2Point memory b2,
        G1Point memory c1, G2Point memory c2,
        G1Point memory d1, G2Point memory d2
    ) internal view returns (bool) {
        uint[24] memory input = [
            a1.X, a1.Y, a2.X[0], a2.X[1], a2.Y[0], a2.Y[1],
            b1.X, b1.Y, b2.X[0], b2.X[1], b2.Y[0], b2.Y[1],
            c1.X, c1.Y, c2.X[0], c2.X[1], c2.Y[0], c2.Y[1],
            d1.X, d1.Y, d2.X[0], d2.X[1], d2.Y[0], d2.Y[1]
        ];
        uint[1] memory out;
        bool success;
        assembly { success := staticcall(sub(gas(), 2000), 8, input, 0x300, out, 0x20) }
        require(success, "SelectiveDisclosureVerifier: Pairing check failed");
        return out[0] == 1;
    }
}
